### ISSUE TITLE
./cmd showing error

### ISSUE THREAD

**Issue by newtonwork** [nuls-io/nuls-v2#315]
![image](https://user-images.githubusercontent.com/52696665/60875434-7cbb1280-a257-11e9-8a06-130b0c9d7ec4.png)

**Comment by samoslab-nuls** [comment]
echo $JAVA_HOME //查看是否是正确的环境变量
确认是否重复配置了JAVA_HOME变量

**Comment by newtonwork** [comment]
@samoslab-nuls now works thanks a lot.
The problem is maven not defined with java home.
