### ISSUE TITLE
Cmd client prints "baglance" instead of "balance"

### ISSUE THREAD

**Issue by nmschorr** [nuls-io/nuls-v2#339]
The chainbox cmd cli tool prints "baglance" instead of "balance".  I believe the offending word can be found in: 
nuls-cmd-client/src/main/java/io/nuls/cmd/client/processor/account/GetAccountProcessor.java 

on or near line 105 in the chainbox branch:
           res.put("baglance",balanceMap);

Example:  

nuls>>> getaccount tNULSeBaMjiyLX3aPdq9oanVhfFb9hp114YEgX { ... "alias" : null, "baglance" : { "available" : "51966.45677167", "total" : "251966.45677167", "freeze" : "200000" 

Steps to Reproduce:
0) Launch the chainbox cmd cli tool in shell
1) Enter:   getaccount <acct number here>
Result: "baglance" is displayed.

**Comment by lijunzhou** [comment]
Thank you, I will fix it in next version.

**Comment by nmschorr** [comment]
Many thanks!
-Nancy
