### ISSUE TITLE
start-dev prints NULS-WALLET STARING

### ISSUE THREAD

**Issue by nmschorr** [nuls-io/nuls-v2#340]
start-dev prints "NULS-WALLET STARING" instead of STARTING.  

It looks like the misspelling is in:  
build/start-mykernel
on line 148.

Steps to Reproduce: (in Chainbox):
0) bring up a shell and cd to the directory with the start-dev script
1) type 'start-dev'
Result: "NULS-WALLET STARING" is displayed.

This should be fixed soon because Kathy updated the Chainbox instructions and used the correct spelling.

**Comment by lijunzhou** [comment]
Thank you, I will fix it in next version.

**Comment by nmschorr** [comment]
Thanks!
