### ISSUE TITLE
check-status prints "REDAY" instead of READY

### ISSUE THREAD

**Issue by nmschorr** [nuls-io/nuls-v2#344]
The cmd cli tool '**check-status**' prints:
"==================RPC REDAY MODULE=================="
and
"======================REDAY MODULE=================="

It should say READY not REDAY.

The lines to fix I believe are in:

build/check-status

on lines 55 and 69.

Steps:
0) In any Chainbox demo bring up shell
1) Start the chainbox with 'start-dev'
2) run 'check-status' in the shell console
Result:  The log in the shell window prints lines with REDAY instead of READY.

This is a cosmetic bug, but when new users see it they might think we can't spellcheck.

**Comment by lijunzhou** [comment]
Thank you, I will fix it in next version.

**Comment by nmschorr** [comment]
Thank you!
