### ISSUE TITLE
example中./package BUILD FAILURE

### ISSUE THREAD

**Issue by syuukawa** [nuls-io/nuls-v2#385]
Downloaded from central: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.jar (4.5 MB at 16 kB/s)
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mail-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/zhouhe/blockchain/chainbox/nuls-chainbox/example/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ mail-example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 33 source files to /Users/zhouhe/blockchain/chainbox/nuls-chainbox/example/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:24 min
[INFO] Finished at: 2019-08-27T15:41:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project mail-example: Fatal error compiling: invalid target release: 11 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
mv: rename target/mail-example.jar to /Users/zhouhe/blockchain/chainbox/nuls-chainbox/example/outer/mail-example-1.0.0.jar: No such file or directory
cp: target/libs: No such file or directory
============ PACKAGE FINISH 🍺🍺🍺🎉🎉🎉 ===============

**Comment by lijunzhou** [comment]
require jdk11.
