### ISSUE TITLE
chinabox中mail-test.html如何在linux中用用浏览器打开

### ISSUE THREAD

**Issue by SongJiaxin95** [nuls-io/nuls-v2#544]
chinabox中NULS-WELLET/Modules/Nuls/mail-example/1.0.0目录下mail-test.html如何在linux中用用浏览器打开，有其他的测试方法吗

**Comment by lijunzhou** [comment]
你的linux系统必须有桌面系统才行。
如何你的linux有可访问的ip，你可以将mail-test.html复制到有浏览器的设备上，将mail-test.html里面访问localhost改为访问linux系统的ip。
