### ISSUE TITLE
cmd script has 'bin' in JAVA_HOME

### ISSUE THREAD

**Issue by nmschorr** [nuls-io/nuls-v2#592]
The cmd script references '/bin' twice:

    JAVA_HOME=dirname "./Libraries/JAVA/JRE/11.0.2/bin";
    JAVA_HOME=cd $JAVA_HOME; pwd
    JAVA="${JAVA_HOME}/bin/java"

so it's looking for ./Libraries/JAVA/JRE/11.0.2/bin/bin/java

Plus the JAVA dir in the Libraries directory in Chainbox isn't there. So between these two things - Chainbox won't run 'cmd'.

Workaround:  Copy a 'JAVA' jre from somewhere else into the Libraries directory.

**Comment by lijunzhou** [comment]
1.运行chainbox打包时，本机环境需要配置JDK环境。
2.使用chainbox打包时，可以通过-J参数指定JRE目录，这个被指定的JRE目录会复制到Libraries/JAVA/JRE/11.0.2 目录下。
3.如果打包时，没有指定JRE目录，也就是打出来的程序包里面不包含JRE，那么运行程序的服务器上需要自带JRE环境，正确配置JAVA_HOME变量。
