### ISSUE TITLE
Chainbox web-wallet and explorer — grizzly error when invoked.

### ISSUE THREAD

**Issue by KathyNorman** [nuls-io/nuls-v2#603]
Chainbox web-wallet and explorer — grizzly error when invoked.
<img width="1423" alt="Screen Shot 2020-06-03 at 10 18 06 PM" src="https://user-images.githubusercontent.com/12434036/83718113-41e96800-a5e9-11ea-95ec-833c2acbaed9.png">
  I followed the README directions in  web-ui for both the nuls-module-web-wallet and  nuls-module-explorer and  after  building the  chain using :”./tools -p nuls-module-web-wallet/ nuls-module-explorer/“ the wallet/explorer failed with a  grizzly error (see included  screen shot).  Also,  I tried “npm install” and after building the chain I still  got the grizzly error.

I am happy to recreate the problem for you.  Thank you!

Note, this is the  commands I used to build the chain:

git clone https://github.com/nuls-io/nuls-chainbox.git chainbox
cd  chainbox/
./tools -t nuls-module-web-wallet
./tools -t nuls-module-explorer
cd nuls-module-web-wallet/
./package
cd ..
cd  nuls-module-explorer/
./package
cd ..
./tools -a smart-contract
./tools -a public-service
./tools -a nuls-api
./tools -s
./tools -p nuls-module-web-wallet/ nuls-module-explorer/

**Comment by lijunzhou** [comment]
打包nuls-module-web-wallet/ nuls-module-explorer/ 需要依赖nodejs环境。
`
[root@images ~]# node -v
v10.1.0
[root@images ~]# npm -v
5.6.0
[root@images ~]# yarn -v
1.17.3
`
