### ISSUE TITLE
Nuls Pro Wallet v2.6.0 .tar Archive Request

### ISSUE THREAD

**Issue by fmanea** [nuls-io/nuls-v2#607]
Is it possible to have a release of Nuls Pro Wallet v.2.6.0 for Linux with the public-service module available?

**Comment by fmanea** [comment]
https://docs.nuls.io/Guide/g_docker.html#premium-wallet

**Comment by fmanea** [comment]
I see that is already available into dockerhub - but if we can receive an archive similar to http://nuls-cn.oss-cn-hangzhou.aliyuncs.com/2.1/NULS_Wallet_pro_linux64_2.1.0.tar.gz  but with the latest version, it would be perfect

**Comment by lijunzhou** [comment]
pro版本需要依赖外部的mongo数据库，所以我建议直接使用docker镜像进行启动，减少安装和配置的难度。
